### ISSUE TITLE
能编译英文版本吗？

### ISSUE THREAD

**Issue by waldronluo** [zhibo/sysuthesis#1]
请问修改pkuthss.cls或者pkuthss-utf8.def能编译出英文版本的论文模板吗？万谢

**Comment by zhibo** [comment]
pkuthss.cls 继承自 ctexbook，ctexbook 是中文模板，英文建议直接使用默认 book，改改封面即可，其实 sysuthesis 主要改动的也是封面，距离真正意义上的 class 还有点远，欢迎各位的 contribute。

**Comment by waldronluo** [comment]
感谢回复。~有时间的话我会把之前改出来的英文版包装好发上来。~
